name: 'Chromatic'

on:
  push:
    branches:
      - develop
      - main
      - 'feature/payform-refactoring'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm i --force

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: chpt_e9d8bd6feaa3a38
