name: Tests

on:
  push:
    branches:
      - develop
      - main
      - 'feature/payform-refactoring'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
       - name: Checkout repository
        uses: actions/checkout@v2.5.1

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --force

      - name: Run Jest tests
        run: npm test

      - name: Run Chromatic tests
        run: npm run chromatic
