name: Tests

on:
  push:
    branches:
      - develop
      - main
      - 'feature/payform-refactoring'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --force

      - name: Run Chromatic tests
        run: npm run chromatic

      - name: Run Jest tests
        run: npm test
